-- E:DEN Planner — SQLite schema (planner-owned database, one file per
-- environment under /var/lib/eden/planner-<env>/, like Budget and Natura).
--
-- The application validates every change first (src/domain) and returns
-- readable errors; the constraints and triggers below are the last line of
-- defence so the canonical data stays consistent whatever the writer.
-- Trigger errors use "CODE: message" so the store can map them.
--
-- Conventions: ids are UUID text generated by the app; dates are ISO
-- 'YYYY-MM-DD' text; timestamps are ISO-8601 UTC text; booleans are 0/1;
-- JSON is text validated with json_valid().

-------------------------------------------------------------------------------
-- Projects, workstreams, members
-------------------------------------------------------------------------------

CREATE TABLE projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
  slug TEXT NOT NULL UNIQUE CHECK (
    length(slug) BETWEEN 1 AND 64
    AND slug NOT GLOB '*[^a-z0-9-]*'
    AND slug NOT LIKE '-%' AND slug NOT LIKE '%-' AND slug NOT LIKE '%--%'
  ),
  description TEXT,
  trello_board_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE workstreams (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- Permanent code, e.g. TEC: 2-10 uppercase letters/digits, starting with a letter.
  code TEXT NOT NULL CHECK (
    length(code) BETWEEN 2 AND 10 AND code GLOB '[A-Z]*' AND code NOT GLOB '*[^A-Z0-9]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (project_id, code)
);

CREATE TABLE members (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- E:DEN Identity user id (eden_…) once the person has signed in.
  eden_user_id TEXT,
  display_name TEXT NOT NULL CHECK (length(trim(display_name)) BETWEEN 1 AND 120),
  email TEXT,
  trello_member_id TEXT,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-------------------------------------------------------------------------------
-- Tasks: Project > Workstream > Task > Subtask (one subtask level)
-------------------------------------------------------------------------------

CREATE TABLE tasks (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- NO ACTION (checked at statement end): a workstream with tasks or a task
  -- with subtasks cannot be deleted, but a project delete still cascades.
  workstream_id TEXT NOT NULL REFERENCES workstreams(id),
  parent_task_id TEXT REFERENCES tasks(id),
  eden_code TEXT NOT NULL,
  title TEXT NOT NULL CHECK (length(trim(title)) BETWEEN 1 AND 200),
  description TEXT,
  owner_member_id TEXT REFERENCES members(id) ON DELETE SET NULL,
  planned_start TEXT CHECK (planned_start IS NULL OR date(planned_start) IS planned_start),
  planned_duration_days INTEGER,
  planned_finish TEXT CHECK (planned_finish IS NULL OR date(planned_finish) IS planned_finish),
  status TEXT NOT NULL DEFAULT 'BACKLOG'
    CHECK (status IN ('BACKLOG', 'READY', 'IN_PROGRESS', 'WAITING_BLOCKED', 'DONE', 'CANCELLED')),
  -- Unvalidated planning values are NULL, never an invented default.
  priority TEXT CHECK (priority IS NULL OR priority IN ('P0', 'P1', 'P2', 'P3')),
  geography TEXT CHECK (
    geography IS NULL OR geography IN ('CECINA_REQUIRED', 'CECINA_PREFERRED', 'REMOTE_OK', 'ANYWHERE')
  ),
  is_milestone INTEGER NOT NULL DEFAULT 0 CHECK (is_milestone IN (0, 1)),
  progress_percent INTEGER CHECK (progress_percent IS NULL OR progress_percent BETWEEN 0 AND 100),
  sort_order INTEGER NOT NULL DEFAULT 0,
  trello_card_id TEXT,
  trello_card_url TEXT,
  trello_sync_status TEXT NOT NULL DEFAULT 'NOT_SYNCED'
    CHECK (trello_sync_status IN ('NOT_SYNCED', 'SYNC_PENDING', 'SYNCED', 'SYNC_ERROR', 'OUT_OF_SYNC')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (project_id, eden_code),

  -- E:DEN code: PREFIX-NNN (task) or PREFIX-NNN.N (subtask), prefix 2-10 chars.
  CHECK (length(eden_code) <= 32),
  CHECK (
    eden_code GLOB '[A-Z][A-Z0-9]*-[0-9][0-9][0-9]*'
    AND instr(eden_code, '-') BETWEEN 3 AND 11
    AND substr(eden_code, 1, instr(eden_code, '-') - 1) NOT GLOB '*[^A-Z0-9]*'
  ),
  CHECK (
    (instr(eden_code, '.') = 0 AND substr(eden_code, instr(eden_code, '-') + 1) NOT GLOB '*[^0-9]*')
    OR (
      instr(eden_code, '.') > 0
      AND substr(eden_code, instr(eden_code, '-') + 1, instr(eden_code, '.') - instr(eden_code, '-') - 1)
          NOT GLOB '*[^0-9]*'
      AND substr(eden_code, instr(eden_code, '.') + 1) GLOB '[1-9]*'
      AND substr(eden_code, instr(eden_code, '.') + 1) NOT GLOB '*[^0-9]*'
    )
  ),
  CHECK ((parent_task_id IS NULL) = (instr(eden_code, '.') = 0)),

  -- Scheduling: planned_finish is derived by the app (Mon-Fri working days).
  CHECK (NOT is_milestone OR planned_duration_days = 0),
  CHECK (is_milestone OR planned_duration_days IS NULL OR planned_duration_days BETWEEN 1 AND 1000),
  CHECK (
    CASE
      WHEN is_milestone THEN planned_finish IS planned_start
      ELSE (planned_finish IS NULL) = (planned_start IS NULL OR planned_duration_days IS NULL)
    END
  ),
  CHECK (planned_finish IS NULL OR planned_finish >= planned_start),
  CHECK (
    is_milestone
    OR (
      (planned_start IS NULL OR strftime('%w', planned_start) NOT IN ('0', '6'))
      AND (planned_finish IS NULL OR strftime('%w', planned_finish) NOT IN ('0', '6'))
    )
  )
);

CREATE INDEX tasks_project_idx ON tasks (project_id);
CREATE INDEX tasks_parent_idx ON tasks (parent_task_id);
CREATE INDEX tasks_workstream_idx ON tasks (workstream_id);

-- Permanent identifiers.
CREATE TRIGGER tasks_eden_code_immutable BEFORE UPDATE OF eden_code ON tasks
  WHEN new.eden_code IS NOT old.eden_code
  BEGIN SELECT RAISE(ABORT, 'EDEN_CODE_IMMUTABLE: E:DEN codes are permanent and cannot be changed'); END;

CREATE TRIGGER tasks_project_immutable BEFORE UPDATE OF project_id ON tasks
  WHEN new.project_id IS NOT old.project_id
  BEGIN SELECT RAISE(ABORT, 'PROJECT_IMMUTABLE: a task cannot move to another project'); END;

-- The parent is encoded in the permanent code (TEC-001.1 -> TEC-001).
CREATE TRIGGER tasks_parent_immutable BEFORE UPDATE OF parent_task_id ON tasks
  WHEN new.parent_task_id IS NOT old.parent_task_id
  BEGIN SELECT RAISE(ABORT, 'PARENT_IMMUTABLE: the parent of a task cannot be changed'); END;

CREATE TRIGGER tasks_milestone_without_subtasks BEFORE UPDATE OF is_milestone ON tasks
  WHEN new.is_milestone = 1 AND old.is_milestone = 0
   AND EXISTS (SELECT 1 FROM tasks c WHERE c.parent_task_id = new.id)
  BEGIN SELECT RAISE(ABORT, 'MILESTONE_WITH_SUBTASKS: a task with subtasks cannot become a milestone'); END;

-- Workstream must belong to the task's project.
CREATE TRIGGER tasks_workstream_project_insert BEFORE INSERT ON tasks
  WHEN NOT EXISTS (SELECT 1 FROM workstreams w WHERE w.id = new.workstream_id AND w.project_id = new.project_id)
  BEGIN SELECT RAISE(ABORT, 'WORKSTREAM_PROJECT_MISMATCH: workstream belongs to another project'); END;

CREATE TRIGGER tasks_workstream_project_update BEFORE UPDATE OF workstream_id ON tasks
  WHEN NOT EXISTS (SELECT 1 FROM workstreams w WHERE w.id = new.workstream_id AND w.project_id = new.project_id)
  BEGIN SELECT RAISE(ABORT, 'WORKSTREAM_PROJECT_MISMATCH: workstream belongs to another project'); END;

-- Subtask rules (checked on insert; parent is immutable afterwards). One
-- trigger with an ordered CASE, because SQLite does not guarantee the firing
-- order of several triggers on the same event.
CREATE TRIGGER tasks_subtask_rules BEFORE INSERT ON tasks
  WHEN new.parent_task_id IS NOT NULL
  BEGIN
    SELECT CASE
      WHEN NOT EXISTS (SELECT 1 FROM tasks p WHERE p.id = new.parent_task_id AND p.project_id = new.project_id)
        THEN RAISE(ABORT, 'PARENT_NOT_FOUND: parent task not found in this project')
      WHEN EXISTS (SELECT 1 FROM tasks p WHERE p.id = new.parent_task_id AND p.parent_task_id IS NOT NULL)
        THEN RAISE(ABORT, 'HIERARCHY_TOO_DEEP: subtasks cannot have subtasks')
      WHEN EXISTS (SELECT 1 FROM tasks p WHERE p.id = new.parent_task_id AND p.is_milestone = 1)
        THEN RAISE(ABORT, 'MILESTONE_WITH_SUBTASKS: milestones cannot have subtasks')
      WHEN NOT EXISTS (
        SELECT 1 FROM tasks p
         WHERE p.id = new.parent_task_id
           AND substr(new.eden_code, 1, instr(new.eden_code, '.') - 1) = p.eden_code
      )
        THEN RAISE(ABORT, 'EDEN_CODE_PARENT_PREFIX: subtask code must start with its parent code')
      WHEN new.workstream_id IS NOT (SELECT p.workstream_id FROM tasks p WHERE p.id = new.parent_task_id)
        THEN RAISE(ABORT, 'SUBTASK_WORKSTREAM_MISMATCH: a subtask is always in its parent''s workstream')
    END;
  END;

CREATE TRIGGER tasks_subtask_workstream_update BEFORE UPDATE OF workstream_id ON tasks
  WHEN new.parent_task_id IS NOT NULL
   AND new.workstream_id IS NOT (SELECT p.workstream_id FROM tasks p WHERE p.id = new.parent_task_id)
  BEGIN SELECT RAISE(ABORT, 'SUBTASK_WORKSTREAM_MISMATCH: a subtask is always in its parent''s workstream'); END;

-- Moving a task to another workstream carries its subtasks along.
CREATE TRIGGER tasks_propagate_workstream AFTER UPDATE OF workstream_id ON tasks
  WHEN new.workstream_id IS NOT old.workstream_id
  BEGIN
    UPDATE tasks SET workstream_id = new.workstream_id, updated_at = new.updated_at
     WHERE parent_task_id = new.id AND workstream_id IS NOT new.workstream_id;
  END;

CREATE TRIGGER workstreams_code_immutable BEFORE UPDATE OF code ON workstreams
  WHEN new.code IS NOT old.code
  BEGIN SELECT RAISE(ABORT, 'WORKSTREAM_CODE_IMMUTABLE: workstream codes are permanent'); END;

CREATE TRIGGER workstreams_project_immutable BEFORE UPDATE OF project_id ON workstreams
  WHEN new.project_id IS NOT old.project_id
  BEGIN SELECT RAISE(ABORT, 'PROJECT_IMMUTABLE: a workstream cannot move to another project'); END;

-------------------------------------------------------------------------------
-- Dependencies: Finish-to-Start, lag in working days >= 0.
-- Cycles are rejected by the store inside the write transaction (SQLite does
-- not allow recursive CTEs in triggers; writers are serialised).
-------------------------------------------------------------------------------

CREATE TABLE task_dependencies (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  predecessor_task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  successor_task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  lag_days INTEGER NOT NULL DEFAULT 0 CHECK (lag_days BETWEEN 0 AND 365),
  created_at TEXT NOT NULL,
  UNIQUE (predecessor_task_id, successor_task_id),
  CHECK (predecessor_task_id <> successor_task_id)
);

CREATE INDEX deps_predecessor_idx ON task_dependencies (predecessor_task_id);
CREATE INDEX deps_successor_idx ON task_dependencies (successor_task_id);
CREATE INDEX deps_project_idx ON task_dependencies (project_id);

CREATE TRIGGER deps_same_project BEFORE INSERT ON task_dependencies
  WHEN NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id = new.predecessor_task_id AND t.project_id = new.project_id)
    OR NOT EXISTS (SELECT 1 FROM tasks t WHERE t.id = new.successor_task_id AND t.project_id = new.project_id)
  BEGIN SELECT RAISE(ABORT, 'DEPENDENCY_PROJECT_MISMATCH: dependency tasks must belong to the same project'); END;

CREATE TRIGGER deps_not_parent_child BEFORE INSERT ON task_dependencies
  WHEN EXISTS (SELECT 1 FROM tasks t WHERE t.id = new.predecessor_task_id AND t.parent_task_id = new.successor_task_id)
    OR EXISTS (SELECT 1 FROM tasks t WHERE t.id = new.successor_task_id AND t.parent_task_id = new.predecessor_task_id)
  BEGIN SELECT RAISE(ABORT, 'DEPENDENCY_PARENT_CHILD: a task cannot depend on its own parent or subtask'); END;

CREATE TRIGGER deps_endpoints_immutable BEFORE UPDATE OF predecessor_task_id, successor_task_id, project_id ON task_dependencies
  WHEN new.predecessor_task_id IS NOT old.predecessor_task_id
    OR new.successor_task_id IS NOT old.successor_task_id
    OR new.project_id IS NOT old.project_id
  BEGIN SELECT RAISE(ABORT, 'DEPENDENCY_IMMUTABLE: dependency endpoints cannot be changed'); END;

-------------------------------------------------------------------------------
-- AI change proposals (Phase 05)
-------------------------------------------------------------------------------

CREATE TABLE change_proposals (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  reason TEXT,
  payload TEXT NOT NULL CHECK (json_valid(payload)),
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPLIED', 'REJECTED')),
  reviewed_by TEXT,
  reviewed_at TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX proposals_project_idx ON change_proposals (project_id);

-------------------------------------------------------------------------------
-- Audit: append-only; written by the store in the same transaction as the
-- change (E:DEN audit contract: "save + audit event -> same transaction").
-- No foreign key: history outlives the rows and projects it describes.
-------------------------------------------------------------------------------

CREATE TABLE audit_events (
  id TEXT PRIMARY KEY,
  project_id TEXT,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('USER', 'CHATGPT', 'CLAUDE', 'SYSTEM', 'TRELLO_SYNC')),
  actor_id TEXT,
  action TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  before_json TEXT CHECK (before_json IS NULL OR json_valid(before_json)),
  after_json TEXT CHECK (after_json IS NULL OR json_valid(after_json)),
  metadata_json TEXT CHECK (metadata_json IS NULL OR json_valid(metadata_json)),
  created_at TEXT NOT NULL
);

CREATE INDEX audit_project_idx ON audit_events (project_id, created_at);
CREATE INDEX audit_entity_idx ON audit_events (entity_type, entity_id);

CREATE TRIGGER audit_events_no_update BEFORE UPDATE ON audit_events
  BEGIN SELECT RAISE(ABORT, 'AUDIT_APPEND_ONLY: audit events are append-only'); END;

CREATE TRIGGER audit_events_no_delete BEFORE DELETE ON audit_events
  BEGIN SELECT RAISE(ABORT, 'AUDIT_APPEND_ONLY: audit events are append-only'); END;
